/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2017-09-13 12:59:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

    	if(session.getAttribute("authorized")!=null){
    		response.sendRedirect("userList.jsp");
    	}
    	session.setAttribute("authorized", null);
	
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\t<title>Admin Login</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.loginForm {\r\n");
      out.write("\t\t\t\tpadding: 5vh;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.input{\r\n");
      out.write("\t\t\t\tpadding : 5px;\r\n");
      out.write("\t\t\t\tmargin : 5px;\t\r\n");
      out.write("\t\t\t\tborder: none;\r\n");
      out.write("\t\t\t\twidth : 90%;\r\n");
      out.write("    \t\t\tborder-bottom: 2px solid #B7B2B1;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.btn{\r\n");
      out.write("\t\t\t\tpadding : 8px;\r\n");
      out.write("\t\t\t\twidth : 90%;\r\n");
      out.write("\t\t\t\tmargin-top : 15px;\r\n");
      out.write("\t\t\t\tborder : none;\r\n");
      out.write("\t\t\t\tbackground-color : #e7e7e7;\r\n");
      out.write("\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t    text-align: center;\r\n");
      out.write("\t\t\t    font-size : 100%;\r\n");
      out.write("\t\t\t    cursor: pointer; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdiv{\r\n");
      out.write("\t\t\t\twidth : 60vh;\r\n");
      out.write("\t\t\t\theight : 50%;\r\n");
      out.write("\t\t\t\ttext-align : center;\r\n");
      out.write("\t\t\t\tbackground-color : #F5F5F5;\r\n");
      out.write("\t\t\t\tmargin : auto;\r\n");
      out.write("\t\t\t\tmargin-top : 20vh;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.btn{\r\n");
      out.write("\t\t\t\tbackground-color : #E0E0E0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.input:hover{\r\n");
      out.write("    \t\t\tborder-bottom: 2px solid #454545;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.input:focus{\r\n");
      out.write("    \t\t\tborder-bottom: 2px solid #454545;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"loginForm\">\r\n");
      out.write("\t\t\t\t<h5><font size=\"3\" color=\"red\">\r\n");
      out.write("\t\t\t\t");
if(session.getAttribute("login")!=null){
					out.print(session.getAttribute("login"));
				}
      out.write("</font></h5>\r\n");
      out.write("\t\t\t<form action=\"AuthenticateUser\">\r\n");
      out.write("\t\t\t\t<h3>Admin Login</h3>\r\n");
      out.write("\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t<font size=\"3\" color=\"red\">\r\n");
      out.write("\t\t\t\t\t\t\t");
	if(session.getAttribute("invalid")!=null){
									out.print(session.getAttribute("invalid"));
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t<input class=\"input\" name=\"user\" type=\"text\" id=\"username\" placeholder=\"Username\"><br>\r\n");
      out.write("\t\t\t\t<input class=\"input\" name=\"pass\" type=\"password\" id=\"password\" placeholder=\"Password\"><br>\r\n");
      out.write("\t\t\t\t<input class=\"btn\" type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
