/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2017-09-11 15:48:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class confirmation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
if(session.getAttribute("nameval")==null){
	response.sendRedirect("index2.jsp");
} 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" style=\"margin: auto;\" border=\"1\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>Registration ID :</th>\r\n");
      out.write("\t<th>");
      out.print( session.getAttribute("reg_idval") );
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr></tr><tr></tr><tr></tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th colspan=\"2\" >Personal Details</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Name :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("nameval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Date of Birth :</td> \r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("dobval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Gender :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("genderval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Personal Email ID :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("pemailval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Company Email ID :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("cemailval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Contact Number :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("contactnoval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>What's App Number : </td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("whatsappnoval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr></tr><tr></tr><tr></tr>\r\n");
      out.write("\r\n");
      out.write("<tr >\r\n");
      out.write("\t<th colspan=\"2\" >Payment Details :</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Payment Mode :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("paymentmodeval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Receipt Number :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("reciptnoval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 if(session.getAttribute("transnoval")!="null")
	out.print("<tr><td>Transaction No :</td><td>"+session.getAttribute("transnoval")+"</td></tr>");

      out.write("\r\n");
      out.write("\r\n");
 if(session.getAttribute("chddnoval")!="null")
	out.print("<tr><td>Cheque/DD No :</td><td>"+session.getAttribute("chddnoval")+"</td></tr>");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Amount Paid :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("amountpaidval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Amount Balance :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("amountbalval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=\"2\" ><button onclick=\"window.print();\">Print</button>\r\n");
      out.write("\t<button onclick=\"window.location.replace('index.jsp')\">Close</button></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
