/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2017-09-11 15:48:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kma.dao.CheckAvailability;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	CheckAvailability check = new CheckAvailability();
	request.getSession().setAttribute("nameval", null);
	request.getSession().setAttribute("Error",null);
	session.setAttribute("login", null);
	session.setAttribute("invalid", null);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>KMA Registration Form</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"externalLib/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"externalLib/css/regForm.css\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\tfunction onLoad() {\r\n");
      out.write("\t\t\t\t\t\t\tif(document.getElementById('cshpaymentmode').checked){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('rcptno').style.display = 'block';\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('amtp').style.display = 'block';\r\n");
      out.write("\t        \t\t\t\t   \tdocument.getElementById('amtb').style.display = 'block';\r\n");
      out.write("\t       \t\t\t\t   \t   \tdocument.getElementById('chddno').style.display = 'none';\r\n");
      out.write("\t       \t\t\t\t   \t\tdocument.getElementById('trnsno').style.display = 'none';\r\n");
      out.write("\t       \t\t\t\t   \t\tdocument.getElementById('chddno').value = null;\r\n");
      out.write("\t       \t\t\t\t \t\tdocument.getElementById('trnsno').value = null;\r\n");
      out.write("\t       \t\t\t\t\t\tdocument.getElementById('rcptno').required = \"required\";\r\n");
      out.write("\t \t\t\t\t   \t\t\tdocument.getElementById('amtp').required = \"required\";\r\n");
      out.write("\t \t\t\t\t  \t\t\tdocument.getElementById('amtb').required = \"required\";\r\n");
      out.write("\t    \t\t\t\t   \t\tdocument.getElementById('chddno').required = false;\r\n");
      out.write("\t       \t\t\t\t   \t\tdocument.getElementById('trnsno').required = false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(document.getElementById('crdpaymentmode').checked){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('rcptno').style.display = 'block';\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('chddno').style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t\t   \tdocument.getElementById('amtp').style.display = 'block';\r\n");
      out.write("\t        \t\t\t\t   \tdocument.getElementById('amtb').style.display = 'block';\r\n");
      out.write("\t       \t\t\t\t   \t   \tdocument.getElementById('trnsno').style.display = 'block';\r\n");
      out.write("\t       \t\t\t\t   \t\tdocument.getElementById('chddno').value = null;\r\n");
      out.write("\t       \t\t\t\t   \t\tdocument.getElementById('trnsno').value = null;\r\n");
      out.write("\t       \t\t\t\t   \t\tdocument.getElementById('rcptno').required = \"required\";\r\n");
      out.write("\t\t\t\t\t\t   \t\tdocument.getElementById('amtp').required = \"required\";\r\n");
      out.write("\t    \t\t\t\t   \t\tdocument.getElementById('amtb').required = \"required\";\r\n");
      out.write("\t    \t\t\t\t   \t\tdocument.getElementById('trnsno').required = \"required\";\r\n");
      out.write("\t    \t\t\t\t   \t\tdocument.getElementById('chddno').required = false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(document.getElementById('chddpaymentmode').checked){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('rcptno').style.display = 'block';\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('trnsno').style.display = 'none';\r\n");
      out.write("\t\t\t\t\t   \t\t\tdocument.getElementById('amtp').style.display = 'block';\r\n");
      out.write("\t\t\t\t\t   \t\t\tdocument.getElementById('amtb').style.display = 'block';\r\n");
      out.write("\t\t\t\t   \t   \t\t\tdocument.getElementById('chddno').style.display = 'block';\r\n");
      out.write("\t\t\t\t   \t\t\t\tdocument.getElementById('rcptno').required = \"required\";\r\n");
      out.write("\t\t\t\t\t   \t\t\tdocument.getElementById('trnsno').value = null;\r\n");
      out.write("\t\t\t\t\t   \t\t\tdocument.getElementById('chddno').value = null;\r\n");
      out.write("\t\t\t\t\t   \t\t\tdocument.getElementById('amtp').required = \"required\";\r\n");
      out.write("\t\t\t\t\t   \t\t\tdocument.getElementById('amtb').required = \"required\";\r\n");
      out.write("\t\t\t\t   \t   \t\t\tdocument.getElementById('chddno').required = \"required\";\r\n");
      out.write("\t\t\t\t   \t   \t\t\tdocument.getElementById('trnsno').required = false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("        \t\t\t\tfunction showcash() { document.getElementById('rcptno').style.display = 'block';\r\n");
      out.write("        \t\t\t\t   \tdocument.getElementById('amtp').style.display = 'block';\r\n");
      out.write("        \t\t\t\t   \tdocument.getElementById('amtb').style.display = 'block';\r\n");
      out.write("       \t\t\t\t   \t   \tdocument.getElementById('chddno').style.display = 'none';\r\n");
      out.write("       \t\t\t\t   \t\tdocument.getElementById('trnsno').style.display = 'none';\r\n");
      out.write("       \t\t\t\t   \t\tdocument.getElementById('chddno').value = null;\r\n");
      out.write("       \t\t\t\t \t\tdocument.getElementById('trnsno').value = null;\r\n");
      out.write("       \t\t\t\t\t\tdocument.getElementById('rcptno').required = \"required\";\r\n");
      out.write(" \t\t\t\t   \t\t\tdocument.getElementById('amtp').required = \"required\";\r\n");
      out.write(" \t\t\t\t  \t\t\tdocument.getElementById('amtb').required = \"required\";\r\n");
      out.write("    \t\t\t\t   \t\tdocument.getElementById('chddno').required = false;\r\n");
      out.write("       \t\t\t\t   \t\tdocument.getElementById('trnsno').required = false;\r\n");
      out.write("       \t\t\t\t   \t}\r\n");
      out.write("       \t\t\t\t\t   \r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\t\tfunction showcard() { document.getElementById('rcptno').style.display = 'block';\r\n");
      out.write("\t\t\t\t\t\t   \tdocument.getElementById('chddno').style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t   \tdocument.getElementById('amtp').style.display = 'block';\r\n");
      out.write("        \t\t\t\t   \tdocument.getElementById('amtb').style.display = 'block';\r\n");
      out.write("       \t\t\t\t   \t   \tdocument.getElementById('trnsno').style.display = 'block';\r\n");
      out.write("       \t\t\t\t   \t\tdocument.getElementById('chddno').value = null;\r\n");
      out.write("       \t\t\t\t   \t\tdocument.getElementById('trnsno').value = null;\r\n");
      out.write("       \t\t\t\t   \t\tdocument.getElementById('rcptno').required = \"required\";\r\n");
      out.write("\t\t\t\t\t   \t\tdocument.getElementById('amtp').required = \"required\";\r\n");
      out.write("    \t\t\t\t   \t\tdocument.getElementById('amtb').required = \"required\";\r\n");
      out.write("    \t\t\t\t   \t\tdocument.getElementById('trnsno').required = \"required\";\r\n");
      out.write("    \t\t\t\t   \t\tdocument.getElementById('chddno').required = false;\r\n");
      out.write("    \t\t\t\t   \t}\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\t\tfunction showchqdd() { document.getElementById('rcptno').style.display = 'block';\r\n");
      out.write("\t\t\t\t   \t\t\tdocument.getElementById('trnsno').style.display = 'none';\r\n");
      out.write("\t\t\t\t   \t\t\tdocument.getElementById('amtp').style.display = 'block';\r\n");
      out.write("\t\t\t\t   \t\t\tdocument.getElementById('amtb').style.display = 'block';\r\n");
      out.write("\t\t\t   \t   \t\t\tdocument.getElementById('chddno').style.display = 'block';\r\n");
      out.write("\t\t\t   \t\t\t\tdocument.getElementById('rcptno').required = \"required\";\r\n");
      out.write("\t\t\t\t   \t\t\tdocument.getElementById('trnsno').value = null;\r\n");
      out.write("\t\t\t\t   \t\t\tdocument.getElementById('chddno').value = null;\r\n");
      out.write("\t\t\t\t   \t\t\tdocument.getElementById('amtp').required = \"required\";\r\n");
      out.write("\t\t\t\t   \t\t\tdocument.getElementById('amtb').required = \"required\";\r\n");
      out.write("\t\t\t   \t   \t\t\tdocument.getElementById('chddno').required = \"required\";\r\n");
      out.write("\t\t\t   \t   \t\t\tdocument.getElementById('trnsno').required = false;\r\n");
      out.write("\t\t\t   \t   \t\t}\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\tfunction copyvaluemail(){\r\n");
      out.write("        \t\t\t\t\tvar ischeck = document.getElementById('sameasabovee').checked;\r\n");
      out.write("        \t\t\t\t\tif(document.getElementById('cemail').value == null || document.getElementById('cemail').value ==\"\"){\r\n");
      out.write("        \t\t\t\t\t\tdocument.getElementById('cemail').value = document.getElementById('pemail').value;\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\tif(document.getElementById('cemail').value !=null || document.getElementById('cemail').value !=\"\"){\r\n");
      out.write("        \t\t\t\t\t\tdocument.getElementById('cemail').value = document.getElementById('pemail').value;\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\tif(!ischeck){\r\n");
      out.write("        \t\t\t\t\t\tdocument.getElementById('cemail').value = null;\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\tfunction copyvaluecontact(){\r\n");
      out.write("        \t\t\t\t\tvar ischeck = document.getElementById('sameasabovec').checked;\r\n");
      out.write("        \t\t\t\t\tif(document.getElementById('wnum').value == null || document.getElementById('wnum').value ==\"\"){\r\n");
      out.write("        \t\t\t\t\t\tdocument.getElementById('wnum').value = document.getElementById('cnum').value;\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\tif(document.getElementById('wnum').value !=null || document.getElementById('wnum').value !=\"\"){\r\n");
      out.write("        \t\t\t\t\t\tdocument.getElementById('wnum').value = document.getElementById('cnum').value;\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\tif(!ischeck){\r\n");
      out.write("        \t\t\t\t\t\tdocument.getElementById('wnum').value = null;\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("      \t\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		//	System.out.println("session_id " + session.getId());
		//	session.setAttribute(session.getId().toString(), session.getId());
			
	
      out.write("\r\n");
      out.write("\t<h3 align=\"right\" style=\"margin-right:10vh;\"><a style=\"cursor : pointer;\" onclick=\"window.open('admin.jsp')\">Admin</a></h3>\r\n");
      out.write("\t<div><header style=\"text-align:center;\"><h1><b>Registration Form</b></h1></header></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form\">\r\n");
      out.write("\t\t<form action=\"CheckAvailability\" enctype=\"multipart/form-data\"  method=\"POST\">\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<label for=\"name\">Name:</label>\r\n");
      out.write("\t\t\t\t<input class=\"fullwidth\" name=\"name\" type=\"text\" placeholder=\"Full Name\" size=50\r\n");
      out.write("\t\t\t\ttitle=\"enter firstname\" pattern=\"[a-zA-Z ]+[a-zA-Z. ]\" title=\"Numbers not allowed\" id=\"name\" required>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>DOB:</label>\r\n");
      out.write("\t\t\t\t<input class=\"fullwidth\" id=\"dob\" name=\"dob\" type=\"date\" placeholder=\"dd-MM-yyyy\" required/>\r\n");
      out.write("\t\t\t\t<br>\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>Personal E-mail:</label>\r\n");
      out.write("\t\t\t\t<input class=\"fullwidth\" id=\"pemail\" name=\"pemail\" type=\"email\" placeholder=\"Personal Email Id\" size=50\r\n");
      out.write("\t\t\t\ttitle=\"Enter valid Email ID\" pattern=\"[a-z0-9._]+@[a-z0-9.-]+\\.[a-z]{2,3}$\" required>\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>Company E-mail:</label>\r\n");
      out.write("\t\t\t\t<input class=\"fullwidth\" id=\"cemail\" name=\"cemail\" type=\"email\" placeholder=\"Company Email Id\" size=50\t\t\r\n");
      out.write("\t\t\t\ttitle=\"Enter valid Email ID\" pattern=\"[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,3}$\" required>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"samediv\">\r\n");
      out.write("\t\t\t\t<input class=\"samecheck\" id=\"sameasabovee\" value=\"true\" id=\"sameasaboveemail\" name=\"sameasaboveemail\" type=\"checkbox\" placeholder=\"Same as peronsal Email ID\" onclick=\"copyvaluemail();\">\r\n");
      out.write("\t\t\t\t<label class=\"sameasabove\" for=\"sameasaboveemail\">Same as above</label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>Contact Number:</label>\r\n");
      out.write("\t\t\t\t<select id=\"cnumpre\" name=\"cc\" size=1>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+91\">+91</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input class=\"contact\" id=\"cnum\" name=\"contactno\" type=\"text\" placeholder=\"Mobile Number\"\r\n");
      out.write("\t\t\t\tpattern=\"[7-9]{1}[0-9]{9}\"\r\n");
      out.write("\t\t\t\ttitle=\"Invalid Contact Number\" maxlength=\"10\" required>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>What'sapp Number:</label>\r\n");
      out.write("\t\t\t\t<select id=\"wnumpre\" name=\"cc\" size=1>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+91\">+91</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input class=\"contact\" id=\"wnum\" name=\"whatsappno\" type=\"text\" placeholder=\"What'sapp Number\"\r\n");
      out.write("\t\t\t\tpattern=\"[7-9]{1}[0-9]{9}\"\r\n");
      out.write("\t\t\t\ttitle=\"Invalid What's app Number\" maxlength=\"10\" required>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"samediv\">\r\n");
      out.write("\t\t\t\t<input class=\"samecheck\" name=\"sameasabovecontact\" type=\"checkbox\" id=\"sameasabovec\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Same as contact number\" onclick=\"copyvaluecontact();\">\r\n");
      out.write("\t\t\t\t<label class=\"sameasabove\" for=\"sameasabovecontact\">Same as above</label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label class=\"gendercaption\" for=\"gender\">Gender:</label>\r\n");
      out.write("\t\t\t\t<div class=\"gendiv\"><input class=\"gender\" id=\"mgender\" type=\"radio\" name=\"gender\" value=\"Male\" required><label class=\"genderlabel\" for=\"mgender\">Male</label></div>\r\n");
      out.write("\t\t\t\t<div class=\"gendiv\"><input class=\"gender\" id=\"fgender\" type=\"radio\" name=\"gender\" value=\"Female\"  ><label class=\"genderlabel\" for=\"fgender\">Female</label></div>\r\n");
      out.write("\t\t\t\t<div class=\"gendiv\"><input class=\"gender\" id=\"ogender\" type=\"radio\" name=\"gender\" value=\"Others\" ><label class=\"genderlabel\" for=\"ogender\">Others</label></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label class=\"paymentcaption\">Payment Details:</label>\r\n");
      out.write("\t     \t \t<div class=\"paydiv\"><input class=\"gender\" id=\"cshpaymentmode\" type=\"radio\" name=\"payment\"\r\n");
      out.write("\t     \t \tvalue=\"Cash\" onclick=\"showcash();\"  required><label class=\"paylabel\" for=\"cshpaymentmode\">Cash</label></div>\r\n");
      out.write("\t\t \t\t<div class=\"paydiv\"><input class=\"gender\" id=\"crdpaymentmode\" type=\"radio\" name=\"payment\" \r\n");
      out.write("\t\t \t\tvalue=\"Card\" onclick=\"showcard();\"  ><label class=\"paylabel\" for=\"crdpaymentmode\">Card</label></div>\r\n");
      out.write("\t\t  \t\t<div class=\"paydiv\"><input class=\"gender\" id=\"chddpaymentmode\" type=\"radio\" name=\"payment\" \r\n");
      out.write("\t\t  \t\tvalue=\"Cheque/DD\" onclick=\"showchqdd();\"><label class=\"paylabel\" for=\"chddpaymentmode\">Cheque/DD</label></div>\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t<input class=\"fullwidth\" name=\"rcptno\" type=\"text\" id=\"rcptno\" style=\"display: none;\"  \r\n");
      out.write("\t        \tplaceholder=\"Slip/Receipt Number\" maxlength=\"30\" >\r\n");
      out.write("\t        \t<input class=\"fullwidth\" type=\"text\" id=\"trnsno\" style=\"display: none;\" value=\"\" \r\n");
      out.write("\t        \tname=\"transno\" placeholder=\"Transaction ID\" maxlength=\"30\">               \r\n");
      out.write("\t        \t<input class=\"fullwidth\" type=\"text\" id=\"chddno\" style=\"display: none;\" value=\"\" \r\n");
      out.write("\t        \tname=\"chddno\" placeholder=\"Cheque/DD Number\" maxlength=\"30\" >\r\n");
      out.write("\t        \t<input class=\"fullwidth\" type=\"number\" id=\"amtp\" style=\"display: none;\" \r\n");
      out.write("\t        \tname=\"amtp\" placeholder=\"Amount Paid\">\r\n");
      out.write("\t        \t<input class=\"fullwidth\" type=\"number\" id=\"amtb\" style=\"display: none;\" \r\n");
      out.write("\t        \tname=\"amtb\" placeholder=\"Amount Balance\">\r\n");
      out.write("\t        \t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<label>Upload Passport size photo:</label>\t\t\t\r\n");
      out.write("\t\t\t\t<input class=\"fullwidth\" id=\"photo\" name=\"photo\" type=\"file\" accept=\"image/*\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"agreediv\">\r\n");
      out.write("\t\t\t\t\t<input id=\"agreement\" name=\"agreement\" type=\"checkbox\" value=\"2\" required><label for=\"agreement\" class=\"agreelabel\">Agree to <a href=\"\">Terms &amp; Conditions</a></label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"actionbtndiv\">\r\n");
      out.write("\t\t\t\t\t<input class=\"actionbtn\" id=\"sub\" type=\"submit\" value=\"SUBMIT\">\r\n");
      out.write("\t\t\t\t\t<input class=\"actionbtn\" id=\"rex\" type=\"reset\" value=\"RESET\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
