/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2017-09-11 15:48:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	session.setAttribute("nameval", session.getAttribute("nameval"));
	session.setAttribute("dobval", session.getAttribute("dobval"));
	session.setAttribute("genderval", session.getAttribute("genderval"));
	session.setAttribute("pemailval", session.getAttribute("pemailval"));
	session.setAttribute("cemailval", session.getAttribute("cemailval"));
	session.setAttribute("contactnoval", session.getAttribute("contactnoval"));
	session.setAttribute("whatsappnoval", session.getAttribute("whatsappnoval"));
	session.setAttribute("pp_image", session.getAttribute("pp_image"));
	
	session.setAttribute("paymentmodeval", session.getAttribute("paymentmodeval"));
	session.setAttribute("reciptnoval", session.getAttribute("reciptnoval"));
	session.setAttribute("transnoval", session.getAttribute("transnoval"));
	session.setAttribute("chddnoval", session.getAttribute("chddnoval"));
	session.setAttribute("amountpaidval", session.getAttribute("amountpaidval"));
	session.setAttribute("amountbalval", session.getAttribute("amountbalval"));
	
	session.setAttribute("whatsappnoa", null);
	session.setAttribute("contactnoa", null);
	session.setAttribute("personal_email", null);
	session.setAttribute("company_email", null);
	session.setAttribute("invalidname", null);
	session.setAttribute("invalidgen", null);
	session.setAttribute("invalidpemail", null);
	session.setAttribute("invalidcemail", null);
	session.setAttribute("invalidcont", null);
	session.setAttribute("invalidwano", null);
	session.setAttribute("invalidimg", null);
	session.setAttribute("invalidimgs", null);
	session.setAttribute("invalidpaym", null);
	session.setAttribute("invalidrcpt", null);
	session.setAttribute("invalidamtp", null);
	session.setAttribute("invalidamtb", null);
	session.setAttribute("invalidtransNo", null);
	session.setAttribute("invalidchqNo", null);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" style=\"margin: auto;\" border=\"1\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th rowspan=\"1\" >Personal Details</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Name :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("nameval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Date of Birth :</td> \r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("dobval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Gender :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("genderval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Personal Email ID :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("pemailval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Company Email ID :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("cemailval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Contact Number :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("contactnoval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>What's App Number : </td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("whatsappnoval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>Payment Details :</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Payment Mode :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("paymentmodeval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Receipt Number :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("reciptnoval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 if(!session.getAttribute("transnoval").toString().contains("null")){
	out.print("<tr><td>Transaction No :</td><td>"+session.getAttribute("transnoval")+"</td></tr>");
	}

      out.write("\r\n");
      out.write("\r\n");
 if(!session.getAttribute("chddnoval").toString().contains("null")){
	out.print("<tr><td>Cheque/DD No :</td><td>"+session.getAttribute("chddnoval")+"</td></tr>");}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Amount Paid :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("amountpaidval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Amount Balance :</td>\r\n");
      out.write("\t<td>");
      out.print( session.getAttribute("amountbalval") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"center\">\r\n");
      out.write("\t\t<button onclick=\"window.location.replace('index2.jsp')\">Edit</button>\r\n");
      out.write("\t\t<form action=\"StoreData\" method=\"POST\"><button type=\"submit\">Submit</button></form>\r\n");
      out.write("\t\t<button onclick=\"window.location.replace('index.jsp')\">Cancel</button></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
