/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2017-03-26 17:03:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kma_registration_form_DB.CheckAvailability;

public final class submit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String nameval = "";
	if(session.getAttribute("nameval")!=null){
		Cookie forName = new Cookie("nameval",session.getAttribute("nameval").toString());
		nameval = forName.getValue();
	}
	
	String dateval = "";
	if(session.getAttribute("dobval")!=null){
		Cookie forName = new Cookie("dobval",session.getAttribute("dobval").toString());
		dateval = forName.getValue();
	}
	
	String pemailval = "";
	if(session.getAttribute("pemailval")!=null){
		Cookie forName = new Cookie("pemailval",session.getAttribute("pemailval").toString());
		pemailval = forName.getValue();
	}
	
	String pemailaval = "";
	if(session.getAttribute("personal_email") != null){
		pemailaval = session.getAttribute("personal_email").toString();
	}
	
	String cemailval = "";
	if(session.getAttribute("cemailval")!=null){
		Cookie forName = new Cookie("cemailval",session.getAttribute("cemailval").toString());
		cemailval = forName.getValue();
	}
	
	String cemailaval = "";
	if(session.getAttribute("company_email") != null){
		cemailaval = session.getAttribute("company_email").toString();
	}
	
	
	String contactval = "";
	if(session.getAttribute("contactnoval")!=null){
		Cookie forName = new Cookie("contactnoval",session.getAttribute("contactnoval").toString());
		contactval = forName.getValue();
	}
	
	String contactaval = "";
	if(session.getAttribute("contactnoa") != null){
		contactaval = session.getAttribute("contactnoa").toString();
	}
	

	String waval = "";
	if(session.getAttribute("whatsappnoval")!=null){
		Cookie forName = new Cookie("whatsappnoval",session.getAttribute("whatsappnoval").toString());
		waval = forName.getValue();
	}
	
	String waaval = "";
	if(session.getAttribute("whatsappnoa") != null){
		waaval = session.getAttribute("whatsappnoa").toString();
	}
	
	String gender = "";
	String genderm = "";
	String genderf= "";
	String gendero = "";
	if(session.getAttribute("genderval")!=null){
		Cookie forName = new Cookie("genderval",session.getAttribute("genderval").toString());
		gender = forName.getValue();
	}
	
	if(gender.contains("Male")){
		genderm="checked";
	}else{
		genderm="";
		if(gender.contains("Female")){
			genderf="checked";
			}else{
				genderf="";
				if(gender.contains("Others")){
					gendero="checked";
				}else{
					gendero="";}
				}
		}
	
	
	String paymentmode = "";
	if(session.getAttribute("paymentmodeval")!=null){
		Cookie forName = new Cookie("paymentmodeval",session.getAttribute("paymentmodeval").toString());
		paymentmode = forName.getValue();
	}

	String paymenttype = "";
	String cash = "";
	String card = "";
	String chdd = "";
	if(session.getAttribute("paymentmodeval")!=null){
		Cookie forName = new Cookie("paymentmodeval",session.getAttribute("paymentmodeval").toString());
		paymenttype = forName.getValue();
	}

	if(paymenttype.contains("Cash")){
		cash="checked";
	}else{
		cash="";
		if(paymenttype.contains("Card")){
			card="checked";
			}else{
				card="";
				if(paymenttype.contains("Cheque/DD")){
					chdd="checked";
				}else{
					chdd="";}
				}
		}
	
	String recval = "";
	if(session.getAttribute("reciptval")!=null){
		Cookie forName = new Cookie("reciptval",session.getAttribute("reciptval").toString());
		recval = forName.getValue();
	}
	
	String transval = "";
	if(session.getAttribute("transnoval")!=null){
		Cookie forName = new Cookie("transnoval",session.getAttribute("transnoval").toString());
		transval = forName.getValue();
	}
	
	String chddval = "";
	if(session.getAttribute("chddnoval")!=null){
		Cookie forName = new Cookie("chddnoval",session.getAttribute("chddnoval").toString());
		chddval = forName.getValue();
	}
	
	String amtpval = "";
	if(session.getAttribute("amountpaidval")!=null){
		Cookie forName = new Cookie("amountpaidval",session.getAttribute("amountpaidval").toString());
		amtpval = forName.getValue();
	}
	
	String amtbval = "";
	if(session.getAttribute("amountbalval")!=null){
		Cookie forName = new Cookie("amountbalval",session.getAttribute("amountbalval").toString());
		amtbval = forName.getValue();
	}

	String imgval = "";
	if(session.getAttribute("photoval")!=null){
		Cookie forName = new Cookie("photoval",session.getAttribute("photoval").toString());
		imgval = forName.getValue();
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
