/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2017-09-13 12:59:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import kma_registration_form_DB.GetNewUsers;

public final class userList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	GetNewUsers x = new GetNewUsers();
	Map<String, ArrayList<Object>> map = new HashMap<String, ArrayList<Object>>();
	map = x.getUsers();
	if(session.getAttribute("authorized")==null){
		response.sendRedirect("admin.jsp");
		session.setAttribute("login", "Please Login");
		
	}else{
		session.removeAttribute("login");
	}
	session.removeAttribute("invalid");
	//System.out.println(map.get("name").size());

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t\t<head>\r\n");
      out.write("\t\t\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"externalLib/bootstrap.min.css\">\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"externalLib/css/sidenavbar.css\">\r\n");
      out.write("\t\t\t\t<script src=\"externalLib/jquery-latest.min.js\"></script>\r\n");
      out.write("\t\t\t\t<title>User's List</title>\r\n");
      out.write("\t\t\t\t<style>\r\n");
      out.write("\t\t\t\t\t.tablediv{\r\n");
      out.write("\t\t\t\t\t\theight : auto;\r\n");
      out.write("\t\t\t\t\t\twidth : auto;\r\n");
      out.write("\t\t\t\t\t\tpadding : 5vh 3vh 1vh 3vh;\r\n");
      out.write("\t\t\t\t\t\tmargin : auto;\r\n");
      out.write("\t\t\t\t\t\tmargin-left : 200px;\r\n");
      out.write("\t\t\t\t\t\tmargin-right : 200px;\r\n");
      out.write("\t\t\t\t\t\tmargin-top : 2vh;\r\n");
      out.write("\t\t\t\t\t\tbackground-color : #F5F5F5;\r\n");
      out.write("\t\t\t\t\t\toverflow: auto;\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t</style>\r\n");
      out.write("\t\t\t\t<script>\t\r\n");
      out.write("\t\t\t\t\t\tfunction approve(row) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"inside approve\");\r\n");
      out.write("\t\t\t\t\t\t\tvar index = row.parentNode.parentNode.rowIndex;\r\n");
      out.write("\t\t\t\t\t\t\tvar row_value = document.getElementById(\"myTable\").rows[index].cells.item(0).innerText;\r\n");
      out.write("\t\t\t\t\t\t\talert(row_value);\r\n");
      out.write("\t\t\t\t\t\t\t$.post('UserApproval', {\"regid\" : row_value, \"action\" : \"add\"}, function (data, status) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif(status==\"success\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"User Approved\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.getElementById(\"myTable\").deleteRow(index);\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"Connection Problem\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfunction disapprove(row) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"Deleting\");\r\n");
      out.write("\t\t\t\t\t\t\talert(\"xxx\");\r\n");
      out.write("\t\t\t\t\t\t\tvar index = row.parentNode.parentNode.rowIndex;\r\n");
      out.write("\t\t\t\t\t\t\tvar row_value = document.getElementById(\"myTable\").rows[index].cells.item(0).innerText;\r\n");
      out.write("\t\t\t\t\t\t\talert(row_value);\r\n");
      out.write("\t\t\t\t\t\t\t$.post('UserApproval', {\"regid\" : row_value, \"action\" : \"delete\"}, function (data, status) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif(status==\"success\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"User Deleted\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.getElementById(\"myTable\").deleteRow(index);\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"Connection Problem\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t\t<body>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"userList.jsp\" class=\"active\">New Registrations</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"registereduser.jsp\">Registered Users</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin.jsp\">Logout</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-left:20%;padding:1px 16px;\" class=\"tablediv\">\r\n");
      out.write("\t\t\t\t<table id=\"myTable\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tRegistration No.\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tName\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tContact No.\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tApprove\r\n");
      out.write("\t\t\t\t\t\t\t</th>\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

							for(int i = 0; i<map.get("name").size(); i++){
								out.println("<tr>");
								out.println("<td>");
								out.println(map.get("regid").get(i));
								out.println("</td>");
								out.println("<td>");
								out.println(map.get("name").get(i));
								out.println("</td>");
								out.println("<td>");
								out.println(map.get("contact").get(i));
								out.println("</td>");
								out.println("<td>");
								out.println("<input class='btn' type='button' value='Approve' onclick='approve(this)'>&emsp;<input class='btn' type='button' onclick='disapprove(this)' value='Disapprove'>" );
								out.println("</td>");
								out.println("</tr>");
							}		
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
